### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by VinceG** [Kocal/vue-web-extension#265]
**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
This repository is great and helpful, Thank You!

There is no documentation and i can't seem to find too much resources in the issues section here. I was wondering what's the normal development workflow is? If i build this once and then drag this to Chrome it installs it, once a change is made we need to build it again and drag it again?

I am just wondering what the process is. 

Thank You.

**Comment by Kocal** [comment]
Hey, thanks for your words :slightly_smiling_face: 

You're right, actually there is not yet a documented development workflow.

In [usage section](https://github.com/Kocal/vue-web-extension#usage), the first two commands only build your extension, and the next two commands watch for modifications and then rebuild your extension:

- If you are in watching **production** mode (`npm run watch`), you will need to reload your extension with this button (![capture d ecran de 2018-07-12 07-12-55](https://user-images.githubusercontent.com/2103975/42613787-08944bdc-85a3-11e8-9aa7-677285bd1a8b.png)) ([chrome://extensions](chrome://extensions)).

- If you are in watching **development** mode (`npm run watch:dev`), the background entry is automatically reloaded (thanks to [webpack-chrome-extension-reloader](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader)) and so you don't have to reload your extension yourself.

By the way, if you are modifying `popup`'s code, you just need to right-click on your extension icon, then click on `Inspect popup`, then press `ctrl+r` to refresh the popup.

**Comment by VinceG** [comment]
@Kocal Thank You!

My process is as follows:

1. npm run watch:dev (in one terminal window)
2. npm run build:dev (another terminal window)
3. Then i select Load Unpacked and select the dist folder.

This seems to work.

Is that the correct process for development?

**Comment by Kocal** [comment]
As said in [usage section](https://github.com/Kocal/vue-web-extension):

> ### `npm run watch:dev`
> Watch for modifications then run `npm run build:dev`.

So the 2nd step of your process is not useful 🙂

**Comment by VinceG** [comment]
OK perfect, thank you.

**Comment by Kocal** [comment]
You're welcome!
