### ISSUE TITLE
The webextension polyfill is not bundled

### ISSUE THREAD

**Issue by yiss** [Kocal/vue-web-extension#310]
Using the boilerplate to make a Firefox extension, the polyfills need to be included: https://github.com/mozilla/webextension-polyfill

I included in my project I can make a pull request with the Webpack configuration

**Comment by yiss** [comment]
Yes exactly

**Comment by Kocal** [comment]
Ok.
Do you think this should be configurable during extension creation? (`vue init ...`) or no?

**Comment by yiss** [comment]
@Kocal Yes I agree

**Comment by yiss** [comment]
Also if the web extension is using content_scripts athis should be added to the manifest.json :
`"content_scripts": [
    {
      "js": [
        "browser-polyfill.js",
        "content.js"
      ]
    }
  ]`

**Comment by Kocal** [comment]
I give you carte blanche for the implementation, but I would like: 
- it should be configurable with the warning message as said before
- anywere in the template, use `chrome.*` or `browser.*` if polyfill are enabled (I'm not sure `chrome.*` is already used in fact ...)
- if template already use `chrome.*`, implement some tests

**Comment by Kocal** [comment]
Released in 1.7.0
