### ISSUE TITLE
Add newtab scenario

### ISSUE THREAD

**Issue by amitbend** [Kocal/vue-web-extension#311]
I'm trying to build an extension that will also incorporate a new tab,
Besides all the great features in this library, I could not find a solution for that. (I'm quite a starter on Vue so I had some hard time to get it running myself)

Is that something on the roadmap?

**Comment by Kocal** [comment]
Hello,

What you want to do is called [Overriding pages](https://developer.chrome.com/extensions/override). 

This is not actually supported by vue-web-extension, but you can follow those steps:
- duplicate the `popup` folder, and give the name of your choice (`page-new-tab` for example), and do some changes inside
- in your `webpack.config.js`, add a new entry, and duplicate this line https://github.com/Kocal/vue-web-extension/blob/master/examples/minimal/webpack.config.js#L62
- add `page-new-tab/new-tab.js` element inside `bundles` array: https://github.com/Kocal/vue-web-extension/blob/master/examples/minimal/scripts/remove-evals.js#L9 
- and then update your `manifest.json` to register your custom new tab

**Comment by amitbend** [comment]
@Kocal thanks for the help, it worked!
