### ISSUE TITLE
Consider adding webextension-polyfill

### ISSUE THREAD

**Issue by davestewart** [Kocal/vue-web-extension#333]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Mozilla supply the following package to make code across browsers more consistent:

- https://github.com/mozilla/webextension-polyfill

It adds the common `browser` global as well as Promise-based behaviour for Chrome instead of callbacks.

Not sure if you would add it by default, or ask during installation.

**Describe alternatives you've considered**
Manually pollyfilling

We only discovered this a few days into extension development, but haven't tested extensively yet.

**Comment by Kocal** [comment]
Released in 1.7.0
