### ISSUE TITLE
Better development workflow

### ISSUE THREAD

**Issue by davestewart** [Kocal/vue-web-extension#334]
**Is your feature request related to a problem? Please describe.**
So, I've been playing with extensions for a while, but this is the first template that has core features like hot reloading working - thanks!

However, developing popups is still very cumbersome. They reload as soon as saved, and the inspector keeps unloading when you save, though I've seen in Firefox that you can force it show.

Nonetheless, you still can't seem to use Vue devtools, even with `Vue.config.devtools = true`.

**Describe the solution you'd like**
We've started to think about building some kind of development sandbox, where we would run popup and options apps directly in the browser, and maybe mock the web extension API objects / calls we need. This way, we're not constantly fighting with the extension framework as we just try to build UI, stores, etc.

Then, I figured, maybe someone has done this, so let's look at the Vue Devtools, and sure enough, they have done some of this:

- https://github.com/vuejs/vue-devtools

Check the "Hacking" section.

Their solution runs a webpack dev server of the devtools app in the browser window itself, so you can build the extension as if building a straight vue extension, at `http://localhost:8100`.

They don't seem to have mocked the extensions API, but they have aa top section where they fire calls at the dev tools.

Perhaps, some kind of tool belt for extension background scripts etc could be developed that does something similar? Not sure if this would be in-page or perhaps using iframes.

**Describe alternatives you've considered**
See above

**Additional context**
I'd be happy to help work on this, maybe as a separate project.

**Comment by Kocal** [comment]
Hey, thank for this message.

There was already an issue about this (#18) but it couldn't be solved. :slightly_frowning_face: 

I just take a new look to https://github.com/vuejs/vue-devtools/issues/120 and @wujunchuan gives a [solution that actually works](https://github.com/vuejs/vue-devtools/issues/120#issuecomment-376454050)!

![capture d ecran de 2018-10-17 06-59-14](https://user-images.githubusercontent.com/2103975/47063267-ac625000-d1da-11e8-8a97-93bb2a32ce39.png)

1. `npm i -g @vue/devtools`
2. `vue-devtools`
3. Copy script tag
4. In `popup.html`, paste the script in `<head>`
5. Update Content Security Policy by adding `http://localhost:XXXX`
6. Disable/Enable your extension on Chrome
7. Open your popup in a tab `chrome-extension://<extension id>/popup/popup.html`
8. Enjoy

**Comment by davestewart** [comment]
Hmm, interesting, I'll take a look!

Does loading the popup in this way allow access to the chrome API? For example, tabs API, content scripts, etc?

**Comment by Kocal** [comment]
Since it's loaded through `chrome-extension://`, yep you have access to chrome API

**Comment by davestewart** [comment]
That's really great news. Thanks both of you for doing all this homework!

But no hot reloading?

What's the alternative? Reload browser?

**Comment by Kocal** [comment]
Unfortunatelly no. :/

Maybe you can ask to [rubenspgcavalcante/webpack-chrome-extension-reloader](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader), this is what we use for bringing HMR to background entry

**Comment by davestewart** [comment]
I think all this info would make a great start to a GitHub Wiki 😄

**Comment by Kocal** [comment]
I wrote a wiki page about development behavior: https://github.com/Kocal/vue-web-extension/wiki/1.-Development-workflow
@davestewart WDYT?

**Comment by davestewart** [comment]
Hey, I'll take a look!

**Comment by Kocal** [comment]
Maybe I can enhance a bit wiki pages with some screenshots :thinking:
