### ISSUE TITLE
Add content.js script

### ISSUE THREAD

**Issue by TribeWeb** [Kocal/vue-web-extension#337]
Great project - thanks!
I am missing being able to use a content.js script. Is there a way of easily integrating a content script into the build in the same that you have done for background.js & popups? Thanks

**Comment by TribeWeb** [comment]
Great project - thanks!
I am missing being able to use a content.js script. Is there a way of easily integrating a content script into the build in the same that you have done for background.js & popups? Thanks

**Comment by Kocal** [comment]
:+1:
