### ISSUE TITLE
npm install warns about 'zip-folder' package 

### ISSUE THREAD

**Issue by budowski** [Kocal/vue-web-extension#338]
**Describe the bug**
After initializing the extension for the first time and running `npm install`, I'm getting `found 3 vulnerabilities`.
When looking into this using `npm audit`, it seems to all originate from the `zip-folder` package.
Running `npm audit fix` doesn't seem to work (getting `3 vulnerabilities required manual review and could not be updated`).

**To Reproduce**
1. `vue init kocal/vue-web-extension my-extension`
2. `cd my-extension`
3. `npm install`

Maybe we should use another package instead, one that has been updated recently?
e.g. [archiver](https://www.npmjs.com/package/archiver) - for example: https://stackoverflow.com/a/51518100/1233767

**Comment by Kocal** [comment]
Thank you, I wasn't even aware of this...😳
I guess it's time to re-enable Dependabot and add checks on CI.. 

I will check this ASAP, thanks for your patch suggestion. 👍
