### ISSUE TITLE
Add option for content script creation when initializing extension

### ISSUE THREAD

**Issue by jonathan-s** [Kocal/vue-web-extension#360]
**Is your feature request related to a problem? Please describe.**
It would be nice if at the start when initializing the extension the content script and everything was in the right place from the beginning. 

**Additional context**
I might make a PR at some point to make that happen. But if anyone else picks up this before that, feel free.

**Comment by chovy** [comment]
I also want to run a vue app from content scripts, so your PR would be welcomed!

**Comment by notflip** [comment]
Is it possible to use a content script with this package? What are the steps to add one (simple one)

**Comment by lastlink** [comment]
You can view my project which I initialized off of a different template then refactored to use this template which has vuejs working in the content scripts. https://github.com/funktechno/git-kanban-enhanced-extension. Note: for content scripts only the `<script></script>` tag doesn't work so I ended up creating a global script component that I inject into the template. the <script> and <template> tags worked fine for me.

Also related to this I wrote my own custom **router** that you can checkout its implementation, b/c the **vue router** does not work well for browser extensions. It forces a hashtag always and I wanted the hashtag to be there only in certain urls and when an extension button was clicked.

**Comment by syifeng** [comment]
I want to add content script into my project, what should i do. I tried to create content just like popup, but failed to run it

**Comment by syifeng** [comment]
> I want to add content script into my project, what should i do. I tried to create content just like popup, but failed to run it

It's function now

**Comment by Kocal** [comment]
This preset now uses https://github.com/adambullmer/vue-cli-plugin-browser-extension which generate content script.
