### ISSUE TITLE
How to use browser.storage and chrome.storage API?

### ISSUE THREAD

**Issue by xternal7** [Kocal/vue-web-extension#361]
I'm trying to port over an existing extension, trying to limit Vue stuff to popup and settings page alone in order to avoid having to rewrite the entire extension. I'm also pretty inexperienced in this.

I've already edited .babelrc to this:

```
{
  "plugins": [
  ],
  "presets": [
    ["@babel/preset-env", {
      "useBuiltIns": false,
      "targets": {
        "esmodules": true,
      },
    }]
  ]
}
```

because otherwise the extension wouldn't build once I started to include existing stuff.

But now I'm running into issues when accessing (browser.)storage API. If I don't try to access `browser.storage`, `browser.storage` will happily exist.

![screenshot_20181227_211142](https://user-images.githubusercontent.com/12505802/50493162-06be2f00-0a1c-11e9-9c36-1a974105241b.png)

If I try to access `browser.storage` in any way, though, it will stop existing:

![screenshot_20181227_211355](https://user-images.githubusercontent.com/12505802/50493206-53096f00-0a1c-11e9-8b2f-f0ef34ea3cdb.png)

(When using 'chrome' instead of 'browser' (for Chrome version of extension), same thing happens. chrome.storage exists until I try to use it, at which point it doesn't).

How can I prevent this behaviour?

**Comment by Kocal** [comment]
Hi, what do you have in your `manifest.json`?

Also, do you use the mozilla polyfill or not?

**Comment by xternal7** [comment]
Yeah, that was it.

I thought I moved 'permission' key between the old manifest and the new. Turns out I forgot to carry it over.

This has to be the dumbest/most embarrasing thing I've done this year. Sorry for wasting your time.
