### ISSUE TITLE
Feat: allow unsafe-eval in Chrome CSP

### ISSUE THREAD

**Issue by Kocal** [Kocal/vue-web-extension#37]
![capture d ecran de 2018-04-11 11-24-14](https://user-images.githubusercontent.com/2103975/38608157-e6aad8bc-3d7a-11e8-8fd7-bb947f2694dd.png)

**Comment by idushii** [comment]
Hi. For work is necessary add in `manifest.json` line `"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"`. God luck.

**Comment by Kocal** [comment]
Oh, I totally forget this issue, thanks :slightly_smiling_face:
