### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by chovy** [Kocal/vue-web-extension#376]
Tried running the following:

`npm i -g vue` and `vue init kocal/vue-web-extension linkbuilding-web-extension` but nothing happens.

$ node -v
v11.3.0

**Comment by Kocal** [comment]
I can't reproduce:
![capture d ecran de 2019-02-19 06-59-41](https://user-images.githubusercontent.com/2103975/52993281-fcb11f00-3413-11e9-91e4-f776187a44d5.png)

What OS do you use?

**Comment by Kocal** [comment]
Ah, I know why, it's because you need to install `vue-cli`, not `vue` itself.

Try with `npm i -g vue-cli` and it should works.

**Comment by chovy** [comment]
That worked. But how do I install the extension in firefox?

**Comment by Kocal** [comment]
Check https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension in "Trying in out" section.

You will have to build the extension and load the `dist/` folder in Firefox
