### ISSUE TITLE
error when using split()

### ISSUE THREAD

**Issue by chovy** [Kocal/vue-web-extension#379]
**Describe the bug**
I get an error when using split

`Module not found: Error: Can't resolve 'core-js/modules/es6.regexp.split'`

**To Reproduce**
Call .split() on text model

**Expected behavior**
should return an array

**Screenshots**
https://gist.github.com/chovy/5124dbed5c8e37c6f0e90a4eb61fcd2b

https://jsfiddle.net/chovy/zt1e5hap/4/ -- here is a fiddle which demonstrates what I'm trying to do.

**Comment by Kocal** [comment]
Same issue than #362, that's weird.. 🤔

**Comment by Kocal** [comment]
Maybe I will add core-js in dependencies to prevent those issues..

**Comment by chovy** [comment]
`npm i -D core-js` fixes it for me.

Might want to make it a dependency, not sure why its needed.

**Comment by chovy** [comment]
i think you should add.
