### ISSUE TITLE
router-link not working

### ISSUE THREAD

**Issue by chovy** [Kocal/vue-web-extension#380]
I have a route for `/campaigns` in pages but when I use `<router-link to="/campaigns">` i get the link but it just loads and empty page with an error about unable to createElement

```
    <router-link to="/campaigns">Campaigns</router-link>
```

```
import PageIndex from './pages/Index';
import Campaigns from './pages/Campaigns';

export default [
  {
    path: '/',
    component: PageIndex,
  },
  {
    path: '/campaigns',
    components: Campaigns,
  }
];

```

**Comment by Kocal** [comment]
I think it's more an issue from vue-router, not this project itself :thinking: 

Can you provide by some code reproduction (like a GitHub repo) and the whole error trace?

**Comment by chovy** [comment]
sure

**Comment by chovy** [comment]
my bad. i had `components:` instead of `component:` it works now.
