### ISSUE TITLE
Can I have a vue app living inside the page?

### ISSUE THREAD

**Issue by chovy** [Kocal/vue-web-extension#383]
It seems the only vue app that is supported with this project is the options page and the popup.

I want a vue app inside the page itself. I have a control panel that I want to interact with the page, but it seems the only place to put the code is in background.js

Can I use vue.js inside background.js? How would I create an app or html?

**Comment by Kocal** [comment]
You can use [content scripts](https://developer.chrome.com/extensions/content_scripts) to interact with your page.

**Comment by chovy** [comment]
Do we have an example of instantiating a vue app from a content script?

**Comment by chovy** [comment]
I've tried this but all i get is a red box. no vue app:

```
import Vue from 'vue';
import store from './store';
import App from './popup/App';
import router from './popup/router';

global.browser = require('webextension-polyfill');

const el = document.createElement('div');
el.style.border = '10px solid red';
el.style.width = '10rem';
el.style.height = '10rem';
el.id = 'lba-app';
document.body.appendChild(el);
// alert(`Hello ${store.getters.foo}!`);

/* eslint-disable no-new */
new Vue({
  el: '#lba-app',
  store,
  router,
  render: h => h(App),
});
```

**Comment by Kocal** [comment]
Weird, can you try to mount the Vue app directly on the component (and not with a selector):

```js
new Vue({
  el: el,
  // ...
});
```

or shorter:

```js
new Vue({
  el,
  //...
});
```

**Comment by mathewcst** [comment]
@chovy did you get it working or some updates that you can share? I'm trying to create a `content script` with Vue, just found this project and it would be nice to have some example on how to use this with content scripts.

**Comment by chovy** [comment]
The problem I see is you need to specify an html page like content.html which loads the app container, the app.js and the css. All we get is a javascript file, no way to load html. So I think if you really wanted to make it work you need to add the css and js into the page using vanilla js. I haven't gotten that far yet.

**Comment by emmanuelmcd** [comment]
@chovy Any update ?

**Comment by chovy** [comment]
yeah. i got it working.

**Comment by emmanuelmcd** [comment]
Can you give me an example of the `content script` your using ? I don't see how to properly mount vue App in the DOM thanks to `content script`.

**Comment by emmanuelmcd** [comment]
I finally got it working with that:

`content.js (Content script)`
```
import Vue from 'vue';
import store from './store';
import App from './popup/App';
import router from './popup/router';

const app = document.createElement('div');
app.id = 'app';
document.body.prepend(app);

/* eslint-disable no-new */
new Vue({
    el: '#app',
    store,
    router,
    render: h => h(App),
});
```
But at this point the style doesn't work so you just have to set this in your `manifest.json`:
```
"content_scripts": [{
    "js": ["content.js"],
    "css": ["content.css"]
  }],
```

**Comment by chovy** [comment]
i'm abandoning this chrome extension. Easier to use a bookmarklet.

**Comment by jianwu** [comment]
> I finally got it working with that:
> 
> ```
> // content.js
> import Vue from 'vue';
> import store from './store';
> import App from './popup/App';
> import router from './popup/router';
> 
> const app = document.createElement('div');
> app.id = 'app';
> document.body.prepend(app);
> 
> /* eslint-disable no-new */
> new Vue({
>     el: '#app',
>     store,
>     router,
>     render: h => h(App),
> });
> ```
> 
> But at this point the style doesn't work so you just have to set this in your `manifest.json`:
> 
> ```
> "content_scripts": [{
>     "js": ["content.js"],
>     "css": ["content.css"]
>   }],
> ```

That actually works for me. Could somebody file a PR to include this into the boilerplate?

**Comment by Jewcub** [comment]
> > I finally got it working with that:
> > ```
> > // content.js
> > import Vue from 'vue';
> > import store from './store';
> > import App from './popup/App';
> > import router from './popup/router';
> > 
> > const app = document.createElement('div');
> > app.id = 'app';
> > document.body.prepend(app);
> > 
> > /* eslint-disable no-new */
> > new Vue({
> >     el: '#app',
> >     store,
> >     router,
> >     render: h => h(App),
> > });
> > ```
> > 
> > 
> > But at this point the style doesn't work so you just have to set this in your `manifest.json`:
> > ```
> > "content_scripts": [{
> >     "js": ["content.js"],
> >     "css": ["content.css"]
> >   }],
> > ```
> 
> That actually works for me. Could somebody file a PR to include this into the boilerplate?


but if you are doing this way, can you start the content script programmatically or just decoratively? The manifest is always declarative, no? I want to have a view app in a new window, so I want to only start it then.
