### ISSUE TITLE
Missing trailing comma in package.json

### ISSUE THREAD

**Issue by JeroenBakker** [Kocal/vue-web-extension#4]
This will make the `npm install` fail during setup.

Right here: https://github.com/Kocal/vue-web-extension/blob/f24e74638bded6c64dff4300e0772956a0145bea/template/package.json#L32

**Comment by Kocal** [comment]
Oh thanks, I'm fixing it.

**Comment by Kocal** [comment]
Fixed in 1479fb5b762ef4bc6b184423bd43f091d68e82a5.
