### ISSUE TITLE
Using env variables inside Vue

### ISSUE THREAD

**Issue by OctaneInteractive** [Kocal/vue-web-extension#422]
Hi, and excellent work!

I've tried creating a ".env" file, and editing Webpack to include additional environmental variables, but both methods fail for similar reasons.

So while environmental variables in the ".env" file pass `npm run watch` I get errors in Chrome if I attempt to use them:

```
mounted () {
  console.log("Index", VUE_APP_VAR)
}
```
>ReferenceError: VUE_APP_VAR is not defined

If I use them inside Webpack, it renders the variables, but then fails to recognise them as such (I was using them in Axios).

What would the correct method be?

**Comment by Kocal** [comment]
You should use env vars from [`process.env`](https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_process_env) variable, like this: `process.env.VUE_APP_VAR`.

Also note that this template is not compatible with vue-cli 3, you are not restricted to name your env vars with `VUE_APP_` if you want to inject them in your bundle.

**Comment by OctaneInteractive** [comment]
>You should use env vars from process.env variable, like this: process.env.VUE_APP_VAR.

Hi, where do I need to declare that? As I said, I tried Webpack and ".env" but both fail.

**Comment by Kocal** [comment]
Can you show me your `webpack.config.js`

**Comment by OctaneInteractive** [comment]
I removed those changes this morning, so now it's the stock Webpack, per the original installation.

**Comment by Kocal** [comment]
I've just found this: https://github.com/mrsteele/dotenv-webpack

It will read your `.env` file and inject env vars into your bundle

**Comment by OctaneInteractive** [comment]
Interesting!

I have _dotenv_ installed, but — as I said — it doesn't work, at least not with the Webpack configuration.

I'll give it a go.

**Comment by Kocal** [comment]
Did you installed and registered the plugin properly?

**Comment by OctaneInteractive** [comment]
I'm using _dotenv_ in another project with no problems, and having followed the same process here it's not working.

I'll install _dotenv-webpack_ and see if that works.

**Comment by OctaneInteractive** [comment]
I had to use:

```
new Dotenv({
  path: './.env',
}),
```
Without the `path` it wouldn't work.

**Comment by Kocal** [comment]
Ah that's weird, because by default [it's alrady `./.env`](https://github.com/mrsteele/dotenv-webpack/blob/master/src/index.js#L31) :thinking:

**Comment by OctaneInteractive** [comment]
> Ah that's weird, because by default [it's alrady `./.env`](https://github.com/mrsteele/dotenv-webpack/blob/master/src/index.js#L31) 🤔

That's what I assumed. Yes, weird.
