### ISSUE TITLE
SASS support?

### ISSUE THREAD

**Issue by OctaneInteractive** [Kocal/vue-web-extension#427]
Hi!

I see there's [support for CSS](https://github.com/Kocal/vue-web-extension/issues/359), and after searching the issues, I see there are commits and merges for SASS, too — how would integrate SASS?

**Comment by Kocal** [comment]
Well, there is already support for Sass/SCSS.

If you want to write it in your Vue component, use this:
```html
<style lang="scss">
/* write SCSS here */
</style>
```

If you want to write your Sass/SCSS in external files, just add a new Webpack entry to them.

**Comment by OctaneInteractive** [comment]
Excellent.

I suppose a _wish_ would be for something similar to:

/styles
--- /css/project.css
--- app1.scss
--- app2.scss
--- app3.scss
--- project.scss

**Comment by Kocal** [comment]
You can totally do it
