### ISSUE TITLE
卡死在vue初始化

### ISSUE THREAD

**Issue by TuDoudong** [Kocal/vue-web-extension#437]
当我进行vue init kocal/vue-web-extension my-extension 初始化的时候 卡在
![image](https://user-images.githubusercontent.com/13363667/59913474-cbd90900-944a-11e9-98a9-18f181c29d16.png)
这一步骤，请问我该如何解决?

**Comment by Kocal** [comment]
Thanks to Google Translate, I was able to understand a bit your problem.

You can either press the `enter` key, or write a description.

**Comment by TuDoudong** [comment]
When I did vue init kocal/vue-web-extension my-extension initialization, I was stuck in project description. When I clicked enter or wrote description, there was still no response
