### ISSUE TITLE
How to use the store in background.js ?

### ISSUE THREAD

**Issue by mde-pach** [Kocal/vue-web-extension#438]
In the `background.js` file generated via the `vue-web-extension` template, there is this line:
`import store from './store'`
But I can't use it with my regular vue App store (the popup one). So I don't know if we need to use any shared store plugin or anything else, but if this is the case, can we have a little line in the README to tell us how to do that ?

Btw, thanks to your awesome work ;)

**Comment by Kocal** [comment]
Hi, you can use this vuex plugin: https://github.com/MitsuhaKitsune/vuex-webextensions

**Comment by Kocal** [comment]
Also see #282

**Comment by mde-pach** [comment]
Thank you and sorry for the duplicated :)
