### ISSUE TITLE
how to print data in popup page

### ISSUE THREAD

**Issue by Goddywu** [Kocal/vue-web-extension#442]
**Describe the bug**

how to print data in popup page

![image](https://user-images.githubusercontent.com/29056050/60416526-a13c3c80-9c10-11e9-87dd-259457273e03.png)

**Comment by Goddywu** [comment]
@Kocal 

and another question: I cannot use background.js's function in popup's vue file

![image](https://user-images.githubusercontent.com/29056050/60416900-8fa76480-9c11-11e9-8b51-0aaa95ba3248.png)
![image](https://user-images.githubusercontent.com/29056050/60416906-9635dc00-9c11-11e9-918a-81e919f75809.png)

**Comment by Kocal** [comment]
Hi, you should right click on your extension icon and then click on `Inspect your popup`. On my computer it's somethink like this:
![Sélection_915](https://user-images.githubusercontent.com/2103975/60417080-c6648700-9bdf-11e9-939f-4c24580aba42.png)

**Comment by Kocal** [comment]
For your other issue (you should have opened a new issue), you can try somethink like this:
```js
mounted() {
  chrome.runtime.getBackgroundPage(bg => {
    bg.test();
  });
}
```

Doc: https://developer.chrome.com/extensions/runtime#method-getBackgroundPage

**Comment by Goddywu** [comment]
thanks for very quick answer! (◦˙▽˙◦)
