### ISSUE TITLE
【question】how to get source HTML of current tab from vue-web-extension

### ISSUE THREAD

**Issue by Goddywu** [Kocal/vue-web-extension#449]
**Describe the question**
I have got the answer of 'Getting the source HTML of the current page from chrome extension', it is the first answer of https://stackoverflow.com/questions/11684454/getting-the-source-html-of-the-current-page-from-chrome-extension?answertab=votes#tab-top . I create simple project and prove it does work.

So I wanna add it in my vue-web-extension project. After several tries, I have no idea how to add it in.

The final project I want is: click the plugin button and print the tab page's html in the index.vue of popup.  (Because I want to send the data to database and extract important page data from it, so I can use axios to send the html to my backend service.)

**Comment by Goddywu** [comment]
Can u help me ...    @Kocal       many thanks.

**Comment by Goddywu** [comment]
@Kocal      😰SOS..

**Comment by Kocal** [comment]
Hi, this is more an issue that you should post on StackOverflow IMO

**Comment by Goddywu** [comment]
For future people who cares,  here is my solution https://www.jianshu.com/p/f230acdbcd1a .
(maybe not best practice)

**Comment by Kocal** [comment]
Thanks for the sharing :)
