### ISSUE TITLE
Correct setup and use of Store mutation-types

### ISSUE THREAD

**Issue by awardx** [Kocal/vue-web-extension#464]
Hi, @Kocal. This might be a completely unrelated question for this topic but I'll try anyway.

In the default setup, actions.js are imported like so

**store/index.js**

```
...
import * as actions from './actions';       // all actions are imported as separate vars
...
```

**actions.js**

```
import * as types from './mutation-types';

export const setFoo = ({ commit }, payload) => {
  commit(types.UPDATE_FOO, payload);
};
```

I think the above approach lacks a fundamental reason why we want to use mutation types file to avoid retyping the names for mutations and actions. 

So what do you think about the following approach instead?

**store/index.js**

```
...
import actions from './actions';       // all actions are imported as separate functions
...
```

**actions.js**

```
import * as types from './mutation-types';

export default {
    [types.UPDATE_FOO] ({commit}, payload) {
 	commit(types.UPDATE_FOO, payload);
    }
}
```

Then anywhere in the extension, we could also import mutation types file and call out the actions using global const names like so

```store.dispatch(types.UPDATE_FOO, 'some value');```

This seems to be more practical in terms of naming and then dispatching/committing our actions/mutations, wouldn't you think so?

**Comment by Kocal** [comment]
Closing as long we don't ship Vuex store ourselves.
