### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by rrfaria** [Kocal/vue-web-extension#468]
**Is your feature request related to a problem? Please describe.**
It is a suggestion to improve project.
 My idea is extract all dependencies like team create-react-app. they have react-scripts and all depencies is inside it, so if I update react-scripts I have the newest dependencies without have to configure webpack or any other thing. I know vue is different but could have this amazing feature.

take a look this article could help create vue-scripts:
https://medium.com/@szer0601/create-react-scripts-create-your-own-react-scripts-without-fork-e73d384c7369

**Comment by Kocal** [comment]
Well, this project is a vue-cli 2 template and so this kind of feature is not supported. 

However you can check at https://github.com/adambullmer/vue-cli-plugin-browser-extension. It's a vue-cli 3 plugin that allow you to build a browser extension too.
Its dependencies and configuration are contained in this plugin too. When you will update the plugin, you will also update its dependencies
