### ISSUE TITLE
Source maps not working properly

### ISSUE THREAD

**Issue by d9k** [Kocal/vue-web-extension#491]
when I run `npm run watch:dev` and open chrome dev tools to debug my extension script I see In devtools (`Sources` tab, `webpack://` folder in sources tree) proper modules names but the code is not the original code from `src` folder.

The observed code contains similar lines:

```
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return
```

How can I run webpack to step through original unprocessed code in DevTools?

**Comment by Kocal** [comment]
Hi, 

You can configure how webpack generate sourcemaps by using the option [`devtool`](https://webpack.js.org/configuration/devtool/).

You can use `cheap-module-eval-source-map` that will display the original lines.

**Comment by d9k** [comment]
@Kocal, thanks a lot! :relieved:
