### ISSUE TITLE
NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by pancevac** [Kocal/vue-web-extension#495]
**Describe the bug**
I'm getting error "TypeError: "NetworkError when attempting to fetch resource."" on Firefox browser when sending request via fetch() method. I also tried using axios, same error. All I know that error is not triggered by CORS because I configure proxy server with disabled CORS. For some reason, browser won't even send request to server (empty network tab) so I guess that problem is in browser.

![fetch error](https://user-images.githubusercontent.com/40486566/67560530-5c866500-f71b-11e9-96d4-954c71743daa.png)

Here is code which triggers the error
```javascript
const url = 'http://localhost:8000/youtube/v3/videos?part=statistics&id=g6YY1ndxu20'
      fetch(url)
        .then(response => console.log(response.json()))
        .catch(err => console.log(err))
```

**Comment by Kocal** [comment]
What permissions do you have defined? Did you allow `localhost:8000`?  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions

**Comment by pancevac** [comment]
Sorry for the late response, indeed, that was a problem, I spent whole day trying to figure out what's going on for such an obvious thing. Thanks a lot!
