### ISSUE TITLE
Uncaught SyntaxError in Chrome after init

### ISSUE THREAD

**Issue by stefanwuthrich** [Kocal/vue-web-extension#500]
**Describe the bug**
After a clean vue init, with router, vuex and axios, i get a:
Uncaught SyntaxError: missing ) after argument list
background.js:1209 (anonymous function):
`var signals = JSON.parse("{"SIGN_CHANGE":"SIGN_CHANGE","SIGN_RELOAD":"SIGN_RELOAD","SIGN_RELOADED":"SIGN_RELOADED","SIGN_LOG":"SIGN_LOG","SIGN_CONNECT":"SIGN_CONNECT"}");`

**To Reproduce**
1. vue init project
2. yarn watch:dev 
3. Load unpacked extension in Chrome (Linux, Version 78.0.3904.97 (Official Build) (64-bit))

**Expected behavior**
No errors after clean vue-init

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: ...
 - OS: Arch based Linux
 - Node.js version: 10.16.0

**Comment by Kocal** [comment]
The issue is comming from webpack-extension-reloader [at this line](https://github.com/rubenspgcavalcante/webpack-extension-reloader/blob/master/src/middleware/wer-middleware.raw.ts#L16), feel free to open a new issue on their repo. 
Thanks

**Comment by Kocal** [comment]
Someone already opened an issue https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/55
