### ISSUE TITLE
how to debug with Vue Devtools?

### ISSUE THREAD

**Issue by heavenkiller2018** [Kocal/vue-web-extension#515]
**Describe the bug**
Vue debug tools can't be found in the debug panel when i want to  debug popup.html page? why?

**Comment by Kocal** [comment]
Hi, sorry for the delay, I took some days off.

The Vue devtool is not supposed to show when you building for production (see https://github.com/vuejs/vue-devtools/blob/dev/README.md#important-usage-notes).

How do you build your extension?

**Comment by MihaiVoinea** [comment]
Hey! Is there any update on this?

Did someone manage to get Vue.js devtools to work?

**Comment by Kocal** [comment]
Hi, I don't remember when we did this, but this is documented on the wiki: https://github.com/Kocal/vue-web-extension/wiki/1.-Development-workflow

However, I agree it's not the best place.. we should add it in a `docs/` folder.
