### ISSUE TITLE
Good afternoon. How can I connect "Vuetify"?

### ISSUE THREAD

**Issue by AlexeyZelenko** [Kocal/vue-web-extension#554]
Good afternoon. How can I connect "Vuetify"?

**Comment by Kocal** [comment]
Hi, did you face an issue while trying to setup Vuetify?

**Comment by AlexeyZelenko** [comment]
Yes

**Comment by Kocal** [comment]
And... what is the issue?

**Comment by AlexeyZelenko** [comment]
I am a beginner programmer. I can not connect it to the project. I would be grateful for your help ...

**Comment by Kocal** [comment]
It's not a problem, I can help you. 
I'm asking to you if you have tried something and faced an issue (so you can post your issue here), or you are just waiting for me to give the solution?

**Comment by AlexeyZelenko** [comment]
one moment... please

**Comment by AlexeyZelenko** [comment]
Installed using Vue Cli .

package.json
{
  "name": "my-extension3",
  "version": "1.0.0",
  "description": "A Vue.js web extension",
  "author": "Oleksii Zelenko <52129260+AlexeyZelenko@users.noreply.github.com>",
  "engines": {
    "node": ">=10"
  },
  "scripts": {
    "lint": "eslint --ext .js,.vue src",
    "prettier": "prettier \"src/**/*.{js,vue}\"",
    "prettier:write": "npm run prettier -- --write",
    "build": "cross-env NODE_ENV=production webpack --hide-modules",
    "build:dev": "cross-env NODE_ENV=development webpack --hide-modules",
    "build-zip": "node scripts/build-zip.js",
    "watch": "npm run build -- --watch",
    "watch:dev": "cross-env HMR=true npm run build:dev -- --watch"
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  },
  "dependencies": {
    "axios": "^0.19.0",
    "vue": "^2.6.10",
    "vue-router": "^3.0.1",
    "vuetify": "^2.2.12",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/runtime-corejs3": "^7.4.0",
    "@types/chrome": "^0.0.74",
    "archiver": "^3.0.0",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.2",
    "copy-webpack-plugin": "^5.1.1",
    "core-js": "^3.0.1",
    "cross-env": "^5.2.0",
    "css-loader": "^3.4.0",
    "ejs": "^2.6.1",
    "eslint": "^6.6.0",
    "eslint-config-prettier": "^6.7.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^3.0.2",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^6.0.1",
    "file-loader": "^5.0.2",
    "husky": "^2.4.0",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.9.3",
    "prettier": "^1.17.1",
    "pretty-quick": "^1.8.0",
    "sass-loader": "^7.1.0",
    "vue-loader": "^15.4.2",
    "vue-template-compiler": "^2.6.10",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.3.10",
    "webpack-extension-reloader": "^1.1.0"
  }
}

**Comment by AlexeyZelenko** [comment]
index.vue
<template>
  <div style="width: 600px; height: 510px">
    <p>Hello world!!!</p>
    <v-banner two-line>
      <v-avatar
              slot="icon"
              color="deep-purple accent-4"
              size="40"
      >
        <v-icon
                icon="mdi-lock"
                color="white"
        >
          mdi-lock
        </v-icon>
      </v-avatar>

      Three line text string example with two actions. One to two lines is preferable. Three lines should be considered the maximum string length on desktop in order to keep messages short and actionable.

      <template v-slot:actions>
        <v-btn text color="deep-purple accent-4">Action</v-btn>
        <v-btn text color="deep-purple accent-4">Action</v-btn>
      </template>
    </v-banner>
    <div v-for="post in posts" :key="post.id">
      <h2>{{ post.title }}</h2>
      <p>{{ post.body }}</p>
    </div>

  </div>
</template>

<script>
export default {
  data() {
    return {
      posts: [],
    };
  },
  async mounted() {
    const res = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=3');
    const posts = await res.json();
    this.posts = posts;
  },
};
</script>

<style lang="scss" scoped>
p {
  font-size: 20px;
}
</style>

**Comment by AlexeyZelenko** [comment]
https://github.com/AlexeyZelenko/my-extension3

**Comment by Kocal** [comment]
I only see `vuetify` as dependency.
Do you tried to following this guide https://vuetifyjs.com/en/getting-started/quick-start?

**Comment by AlexeyZelenko** [comment]
Error: ENOENT: no such file or directory, open 'C:\Users\User\PhpstormProjects\google1\my-extension3\public\index.html'

**Comment by Kocal** [comment]
So it's not related with Vuetify right? What is this `public/index.html` file?

**Comment by AlexeyZelenko** [comment]
At startup $ vue add vuetify

**Comment by tristanbes** [comment]
@AlexeyZelenko as a young developper, it's important you learn how to get help:

Opening an issue on a library/extension you use, and asking for help on something completely unrelated to the library or extension itself is not something you want to do if you want to get help.

What you should try instead:
- Read at least the "quick start" documentation of the thing you use or try to install
- Identify what is the source of the problem (when it's happening might be a good starting point)
- Search for similar issues on the library github repositories
- If you think it's a bug, you should open an issue with a lot of context (what you did, how you did it, what is happening, what is your environment, the versions you have etc...)
- If you need help, i'd suggest you post your issue on stackoverflow. Note that, if you provide too little context, to little information, you won't recieve any help.

**Comment by AlexeyZelenko** [comment]
Thank you very much.

**Comment by Kocal** [comment]
> At startup $ vue add vuetify

`vue add` is specific to vue-cli 3 and 4, see https://cli.vuejs.org/guide/plugins-and-presets.html for more info.

However this template `kocal/vue-web-extension` is specific to vue-cli 2 (see [requirements](https://github.com/Kocal/vue-web-extension#requirements)).

Now you have two solutions:
1. use this template https://github.com/adambullmer/vue-cli-plugin-browser-extension which is compatible with vue-cli 3, you will be able to run `vue add vuetify`
2. keep using this template but do a manual installation by following this section https://vuetifyjs.com/en/getting-started/quick-start#webpack-install

**Comment by AlexeyZelenko** [comment]
Thank you I really liked your (vue-web-extension). Thank you, you really clarified the situation. Thank you for your patience and wisdom. Success in further projects.
