### ISSUE TITLE
Multiple content scripts

### ISSUE THREAD

**Issue by smileypop** [Kocal/vue-web-extension#559]
**Is your feature request related to a problem? Please describe.**
It seems that only one content script can be loaded into `entry: { content:`

**Describe the solution you'd like**
I would like to use multiple `content_scripts` that have different `matches`.

**Comment by Kocal** [comment]
Hi,

I don't think you are limited to one content script, you can add multiple webpack entries and configure your `manifest.json`.

In your `webpack.config.js`:
```js
const config = {
  // ...
  entry: {
    content_script_1: './content-script/1.js',
    content_script_2: './content-script/2.js',
    content_script_3: './content-script/3.js',
  },
  // ...
}
```

and in your `manifest.json`:
```json
{
  "content_scripts": [
    {
      "matches": ["*://*.mozilla.org/*"],
      "js": ["content_script_1.js"]
    },
    {
      "matches": ["*://*.mozilla.org/*"],
      "js": ["content_script_2.js"]
    },
    {
      "matches": ["*://*.mozilla.org/*"],
      "js": ["content_script_3.js"]
    }
  ]
}
```

**Comment by smileypop** [comment]
Unfortunately, that does not work.

The webpack config will build any entry key to the path specified.
But it builds extra code inside the file with the key named `content`. It does not add this code to other named keys.

Try to build with this config and you'll see what I mean.


```
const config = {
  // ...
  entry: {
    content: '.content-script/0.js'
    content_script_1: './content-script/1.js',
    content_script_2: './content-script/2.js',
    content_script_3: './content-script/3.js',
  },
  // ...
}

```

The generated content script in the dist folder will have extra code at the top.

**Comment by smileypop** [comment]
I apologize. You were correct. The error was in my manifest.json, not the webpack config. Thank you for your help.
