### ISSUE TITLE
"chrome.tabs.sendMessage" sends undefined on production build

### ISSUE THREAD

**Issue by leemyongkun** [Kocal/vue-web-extension#572]
```
//caller
chrome.tabs.sendMessage(tabId, {OPTION}, callbacker => {
// ... deal with returnData here ...
returnData // <-- undefined
})

//Callee
chrome.runtime.onMessage.addListener(async (msg, sender, sendResponse)
// ... business logic ...
sendResponse(returnData);
return true;
```

When I run the above code on dev mode npm run watch:dev the code works as expected and returnData is received in the caller method.

However when the code is bundled in production mode with npm run build the caller method receives returnData as undefined.

Is there a fix to this issue?

Thanks in advance.

**Comment by Kocal** [comment]
Hi,

I don't understand where your `returnData` is defined in your `chrome.tabs.sendMessage` callback.

The following code should work:

```
chrome.runtime.onMessage.addListener(function(message, sender, sendResponse) {
  if (message.type === 'foo') {
     sendResponse({ received: true });
     return;
  }

  sendResponse({ error: 'Unknown message type' });
});

chrome.tabs.sendMessage(tabId, { type: 'foo' }, response => {
    console.log(response);
});
```

See https://developer.chrome.com/extensions/tabs#method-sendMessage and https://developer.chrome.com/extensions/runtime#event-onMessage

**Comment by selvinkuik** [comment]
@Kocal I am able to reproduce this issue.

In my `/src/content/App.vue` I have:

```
mounted() {
  chrome.runtime.sendMessage({ action: 'get_something' }, something => {
    remoteLog(something)
  })
}
```

And in my `/src/background.js` I have:

```
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action == 'get_something') {
    sendResponse('Hello world')

    return true
  }
})
```

When I `yarn run watch:dev` my `remoteLog` prints `'Hello world'`. But when I `yarn build` and run, I get `undefined`.

**Comment by selvinkuik** [comment]
@Kocal I am able to reproduce this issue.

In my `/src/content/App.vue` I have:

```
mounted() {
  chrome.runtime.sendMessage({ action: 'get_something' }, something => {
    remoteLog(something)
  })
}
```

And in my `/src/background.js` I have:

```
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action == 'get_something') {
    sendResponse('Hello world')

    return true
  }
})
```

When I `yarn run watch:dev` my `remoteLog` prints `'Hello world'`. But when I `yarn build` and run, I get `undefined`.

**Comment by Kocal** [comment]
Hi, can you try using `browser.` instead of `chrome.`?

**Comment by wangjue666** [comment]
hi, This is the build problem of webpack!.

```
chrome.runtime.onMessage.addListener(async (msg, sender, sendResponse){
  awiat some_business_logic()
  sendResponse(returnData);
  return true;
}
```
webpack build after will be made like this

```
chrome.runtime.onMessage.addListener(async (msg, sender, sendResponse){
  awiat some_business_logic()
  return  sendResponse(returnData);
}
```

That's why sends undefined on production build

so, You should adjust your code like this

```
chrome.runtime.onMessage.addListener((msg, sender, sendResponse){
  some_business_logic(msg).then(sendResponse)
  return true;
}
```

So it can work normally！
