### ISSUE TITLE
Navigation Guards don't work on extension

### ISSUE THREAD

**Issue by vinibispo** [Kocal/vue-web-extension#577]
Hey @Kocal 
**Describe the bug**
When I add 
``
router.beforeEach((to, from, next)=> {
...
}
)
``
The extension crashes
**To Reproduce**
1. go to src/popup/router/index.js
2. add ``
router.beforeEach((to, from, next)=> {
...
}
)
``
3. look at your extension in chrome

**Expected behavior**
Aplly behavior of navigation guards

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: ...
 - OS: Linux/ Ubuntu 18.04
 - Node.js version: 12.16.1

**Comment by vinibispo** [comment]
The error was me, sorry

**Comment by Kocal** [comment]
Hi, no problem!
What was the issue and how did you fix it? Maybe it will help some people facing the same issue.

Thanks!

**Comment by vinibispo** [comment]
I was putting in router/index.js litterally ``router.beforeEach((to, from, next)=> {} )``
And that stops ``vue-router``, because ``vue-router`` loses himself, because that needs ``router.beforeEach((to, from, next) => {
next()
}
)``` unless
