### ISSUE TITLE
The function defined in background.js cannot be called.

### ISSUE THREAD

**Issue by kurohoan** [Kocal/vue-web-extension#578]
The function defined in background.js from popup.js
I want to call it using chrome.extension.getBackgroundPage (), but the error "not a function" is displayed, probably because the function name of background.js has changed after the build.
Is there a way around this?

**Comment by Kocal** [comment]
From my experience, I consider using `chrome.extension.getBackgroundPage()` is a bad practice. First it does not work on private mode, on Firefox you can face the [issue `TypeError: can't access dead object`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object), and you have to declare your functions/variables globally in your background to access them through `chrome.extension.getBackgroundPage()`, that's not ideal.

If you want to communicate between your background and your popup, you should use `chrome.tabs.sendMessage()` and `chrome.runtime.onMessage.addListener()`.
See https://developer.chrome.com/extensions/messaging and https://github.com/Kocal/vue-web-extension/issues/572#issuecomment-618190569 for an example.

But if you really want to keep using `chrome.extension.getBackgroundPage()`, then you have to update your `webpack.config.js` and tell to the Webpack minimizer to keep function names. See:
- https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions
- https://webpack.js.org/configuration/optimization/#optimizationminimizer
- https://webpack.js.org/plugins/terser-webpack-plugin/

**Comment by kurohoan** [comment]
Thank you very much.
I changed the code, but when I press the start button, chrome.runtime.onMessage.addListener () in background.js does not work.
Is something wrong?

Also, mouted's setinterval is not working. Is this also written incorrectly?

popup.js
`
<template>
  <div class="popup-area">
        <div class="btn-area">
            <button @click="Action('start')" id="start_btn">Start</button>
            <button @click="Action('stop')" id="stop_btn">Stop</button>
        </div>
    </div>
</template>

<script>
export default {
  data() {
    return {
      status_list:{
          none: 'stopping',
          wait: 'waiting',
          run: 'running',
          error: 'error'
      },
      status: 'none',
      logs: [],
    };
  },
  methods:{
    mounted: function() {  
      setInterval( ()=> {
        this.status = this.Action('get_status');
        console.log(this.status);
      }, 500);

    },
    Action: function(action){
      var res = chrome.runtime.sendMessage({
          action: action
      });
      return res;
    },
  }
};
</script>
`

background.js
`
chrome.runtime.onMessage.addListener( function (m, s, r) {
    console.log(m);
});

`

**Comment by kurohoan** [comment]
thank you.

**Comment by Kocal** [comment]
> I changed the code, but when I press the start button, chrome.runtime.onMessage.addListener () in background.js does not work.

I dont know if it's related, but this code is not correct:
```js
var res = chrome.runtime.sendMessage({
    action: action
});
```

This function does not return your response, see [`chrome.runtime.sendMessage`](https://developer.chrome.com/extensions/runtime#method-sendMessage).

To get the response, you should use a callback like this:
```js
chrome.runtime.sendMessage({ action: action }, function(res) {
    console.log(res);
});
```

But then you cannot really do anything with this value, you can't return it, except if you use a promise:
```js
return new Promise(resolve => {
	chrome.runtime.sendMessage({ action: action }, function(res) {
	    resolve(res);
	});
});
```

then you can call `Action` like this:
```js
this.Action('get_status').then(status => {
    this.status = status;
});
```

> Also, mouted's setinterval is not working. Is this also written incorrectly?

`mounted` is a Vue [instance lifecycle hook](https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks) and should be  declared at the root of your component, not in `methods` object:
```vue
<template>
  <!-- ... -->
</template>

<script>
export default {
    mounted() {
       // ...
    },
    methods: {
       // ...
    }
}
</script>
```

**Comment by Kocal** [comment]
Ah, did you delete your message because it was resolved? What did you do to fix it?

**Comment by kurohoan** [comment]
We have solved the issue of chrome.runtime.onMessage.addListener ().
I was confused that it wasn't working because I made a mistake in the place where I saw console.log.
I'm sorry.
Thank you very much.
