### ISSUE TITLE
setInterval () in mounted () does not execute.

### ISSUE THREAD

**Issue by kurohoan** [Kocal/vue-web-extension#579]
The code below is written, but setInterval () is not executed. Is there any mistake in the description method?

popup.js
```
<script>
export default {
  methods:{
    mounted: function() {  
      setInterval( ()=> {
        console.log('test');
      }, 500);
    },
  }
};
</script>
```

**Comment by Kocal** [comment]
As said in https://github.com/Kocal/vue-web-extension/issues/578#issuecomment-628415438, `mounted` is a Vue [instance lifecycle hook](https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks) and should be  declared at the root of your component, not in `methods` object:
```vue
<template>
  <!-- ... -->
</template>

<script>
export default {
    mounted() {
       // ...
    },
    methods: {
       // ...
    }
}
</script>
```

**Comment by kurohoan** [comment]
I didn't notice that there was a 'mounted' in the'method '.
Thank you very much.
I'll fix it.

**Comment by kurohoan** [comment]
It worked fine.
Thank you very much.
