### ISSUE TITLE
Load environment variables from files

### ISSUE THREAD

**Issue by quannetwork** [Kocal/vue-web-extension#583]
For now, I followed this [official guide ](https://cli.vuejs.org/guide/mode-and-env.html) to set up the environment variables, then I ran the `npm run watch:dev`, but the `process.env.VUE_APP_NOT_SECRET_CODE` still `undefined`.

So are there any ways to make it work? Thanks in advance.

**Comment by Kocal** [comment]
That's because this template is only compatible with vue-cli 2, not for vue-cli 3+.

You can implement this behavior yourself by using the [`DotEnv` plugin](https://github.com/mrsteele/dotenv-webpack), for example.

**Comment by quannetwork** [comment]
Thanks @Kocal, I did it <3
