### ISSUE TITLE
Undefined browser variable when declare it inside Vuex

### ISSUE THREAD

**Issue by quannetwork** [Kocal/vue-web-extension#584]
When I declare a browser variable to get a local storage value, like this,

```
browser.storage.local.get('accessToken').then(result => {
      accessToken = result.accessToken;
    });
```

it shows `Uncaught ReferenceError: browser is not defined`, but when I call it inside another class, or a Vue component, it works. For example, my `auth.service.js` file:

```
/* eslint-disable class-methods-use-this */
import axios from 'axios';

const API_URL = 'http://example.com/api';

class AuthService {
  login(user) {
    return axios
      .post(`${API_URL}/token`, {
        email: user.email,
        password: user.password,
      })
      .then(response => {
        if (response.data) {
          browser.storage.local.set({ accessToken: response.data });
        }
        return response.data;
      });
  }
}

export default new AuthService();
```

**Comment by quannetwork** [comment]
Found it, it turns out I have to import the `webextension-polyfill`.

```
global.browser = require('webextension-polyfill');
```

**Comment by sorxrob** [comment]
I always get `Cannot read property 'local' of undefined` but I've imported the `webextension-polyfill`.

Any idea?

**Comment by Kocal** [comment]
Do you have set the permission `storage` in your manifest.json?

**Comment by sorxrob** [comment]
Yep, that's the problem. Silly me
