### ISSUE TITLE
Add build option for different browsers

### ISSUE THREAD

**Issue by quannetwork** [Kocal/vue-web-extension#585]
I think it would be better if you could add build option for different browsers, something like:

Development
```
npm run dev chrome
npm run dev firefox
npm run dev edge
npm run dev opera
```
Build
```
npm run build chrome
npm run build firefox
npm run build edge
npm run build opera
```

For Firefox and Edge, it doesn't need polyfill.

**Comment by spekulatius** [comment]
As far as I know it should work for Chrome, Firefox and Edge out of the box. Not sure about Opera. Is your goal to build different packages and keep the size for each at a minimum?

**Comment by quannetwork** [comment]
Yes, it is, I also need to export the crx, zip file, etc.. Actually I was inspired by [webextension-toolbox](https://github.com/webextension-toolbox/webextension-toolbox).

**Comment by spekulatius** [comment]
Ah okay. So it would sign the applications instead of having it signed as part of the upload. Without having any detailed understanding of the required steps to do so it sounds like quite a bit of work. What is the advantage for signing the extension locally?

**Comment by quannetwork** [comment]
I think I could integrate it into a CI, CD pipeline. Something more automatical.

**Comment by spekulatius** [comment]
Ah okay. The current production workflow allows for automatic builds using Travis. But it doesn't include the signing - that's manual using the extension stores. Once you got the signed packages wouldn't you need to upload it manually still?

**Comment by quannetwork** [comment]
Yeah, that makes sense. My idea is overengineered :(

**Comment by spekulatius** [comment]
It's okay. It's interesting as an idea itself, just wondering what the advantage at the end of the day is.
