### ISSUE TITLE
Documentation site?

### ISSUE THREAD

**Issue by spekulatius** [Kocal/vue-web-extension#586]
Hey @Kocal 

again, thank you for all the work in building this! Great work!

I've just check for Vue devtool support and stumbled upon an old issues with the solution. I was wondering if you think it makes sense to add a documentation website for these things. Sites seem to work better than the wiki (which gets forgotten often). 

I've built a number of [vuepress](https://vuepress.vuejs.org/) sites, these sites don't require any on-going work - it's pretty much just markdown files living with the code. Hosting is free with Netlify too. If you are interested, I could prepare one as a PR with some useful VuePress configuration/plugins. Then you would need to only configure Netlify for the free hosting (5 minutes). Comes with a free sub-domain or under any of your (sub-)domains, up to you of course.

This way we would have a website document previous questions and solutions, maybe show-case projects, etc. This could reduce the work involved with support.

Let me know what you think,
Peter

**Comment by Kocal** [comment]
Hi @spekulatius,

Why not, it would be a better solution than the wiki (I don't link the wiki, I don't know why I've started to use it :sweat_smile:) :+1: 

I've already a number of docs/sites on Netlify built with Vuepress, so don't worry for technical part :slightly_smiling_face: 

The only this _I want_, is to have a separate `package.json` for the documentation (e.g.: `docs/package.json`), I don't want to have vuepress to be installed aside project's dep/dev-deps to prevent conflicts (I've already encountered issues with Babel...).

When the site will be up, I will:
- add it in the repo desc
- add pr builder for netlify
- update the wiki and add redirection to the doc

**Comment by spekulatius** [comment]
Awesome, thanks for merging this in @Kocal. I'll add a few more things to the docs over the next days. Let's close this to clean up.
