### ISSUE TITLE
Svg files aren't displayed

### ISSUE THREAD

**Issue by artrayd** [Kocal/vue-web-extension#594]
**Describe the bug**
SVG images aren't loading 

**To Reproduce**
```
/*  CSS */
/* image is not displayed */
.png {
  background: url('./../assets/test.png') center center no-repeat;
}

/* image displayed */
.svg {
  background: url('./../assets/test.svg') center center no-repeat;
}
```

**Expected behavior**
SVG file should be displayed

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: 1.0.3
 - OS: MacOS
 - Node.js version: v12.16.1

**Additional context**
I guess solution is to make some changes inside webpack.config.js, but I am not sure about this

**Comment by Kocal** [comment]
Hi,

Normally .svg files should [be handled correctly](https://github.com/Kocal/vue-web-extension/blob/master/template/webpack.config.js#L47-L56), what did you change?

After compilation (and without your local patch), can you show me how is transformed `url('./../assets/test.svg')`?

**Comment by artrayd** [comment]
Hi Kocal, thank you for anwsering

It transforms to  "url(/images/popup/assets/tut-bombed.svg) center center no-repeat"

The same image from the same folder in .png extension works very well, but svg files aren't displayed (

**Comment by Kocal** [comment]
Is there a file at `<your project>/dist/images/popup/assets/tut-bombed.svg`?

Can you access it through `chrome-extension://<extension id>/images/popup/assets/tut-bombed.svg`?

**Comment by artrayd** [comment]
Kocal, yes, I found svg files there, but here is the code I found inside every svg file, that's why it's not working. But I can't understand why that happens and fix it. 

module.exports = __webpack_public_path__ + "/fonts/popup/assets/asteroid.svg;

**Comment by Kocal** [comment]
Hum, that's probably because there is two rules for `.svg` files: https://github.com/Kocal/vue-web-extension/blob/master/template/webpack.config.js#L47-L65 ... but I'm not sure.

Can you try to remove `|svg` from the 2nd rule?

**Comment by artrayd** [comment]
That worked, thank you for support and your awesome project!

Removed at `|svg` from this line:
`test: /\.(woff(2)?|ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,`
