### ISSUE TITLE
Issue integrating typescript

### ISSUE THREAD

**Issue by UchennaOkafor** [Kocal/vue-web-extension#595]
I am currently using this template for my chrome extension, but I now want to switch to using Typescript.

I looked at the Typescript config file and I already see an issue with it and the way this template works

tsconfig.json
`{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "sourceMap": false,
        "rootDir": "src",
        "outDir": "dist/js",
        "noEmitOnError": true,
        "typeRoots": [ "node_modules/@types" ]
    }
}`

but I fail how the typescript config file would integrate with this templates webpack.config.js file.

Any help? Thanks.

**Comment by Kocal** [comment]
Hi,

I've used this template with TypeScript and I have no problem.

Be sure to:
- have TypeScript dependencies installed (`typescript ts-loader`)
- configure Webpack and `ts-loader`, you need to add a new rule in `module.rules`:
```js
const config = {
  // ...
  module: {
    rules: [
      // ...
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
        options: {
          appendTsSuffixTo: [/\.vue$/],
        },
      },
    ]
  }
}
```
- and configure TypeScript, this is my `tsconfig.json` I am using:
```json
{
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "built",
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es2017",
    "sourceMap": true,
    "strict": true,
    "noImplicitReturns": true,
    "allowJs": true
  },
  "include": ["src/**/*.ts", "src/**/*.vue"],
  "exclude": ["node_modules"]
}
````

**Comment by UchennaOkafor** [comment]
Thank you so much for your contribution to this project, I didn't expect such a quick reply.

**Comment by mykola-zomchak** [comment]
> * configure Webpack and `ts-loader`, you need to add a new rule in `module.rules`:
> 
> ```js
> const config = {
>   // ...
>   module: {
>     rules: [
>       // ...
>       {
>         test: /\.tsx?$/,
>         loader: 'ts-loader',
>         exclude: /node_modules/,
>         options: {
>           appendTsSuffixTo: [/\.vue$/],
>         },
>       },
>     ]
>   }
> }
> ```
Where should I put this?

**Comment by Kocal** [comment]
In the `webpack.config.js` if you still use the Vue-CLI 2 boilerplate (v1).
If you use the Vue-CLI 3+ preset (v2) you don't have to do this.

**Comment by mykola-zomchak** [comment]
@Kocal 
Thanks for quick response
I installed dependencies and copied tsconfig.json ad you provided.
But I get errors:
![image](https://user-images.githubusercontent.com/39236497/97867119-e8ab6f00-1d15-11eb-8b08-c8063bd4f264.png)
![image](https://user-images.githubusercontent.com/39236497/97867147-f4973100-1d15-11eb-8431-ddd5b17e5fb0.png)

**Comment by Kocal** [comment]
- 1st screenshot: I don't know
- 2nd screenshot: You need to tell to TypeScript how it should type `.vue` files. Typically this can be done with the `vue-shims.d.ts` file, see https://github.com/microsoft/TypeScript-Vue-Starter/blob/master/src/vue-shims.d.ts
- 3rd screenshot: See https://github.com/mozilla/webextension-polyfill#usage-with-typescript

**Comment by mykola-zomchak** [comment]
I'm fairly new to typescript and bundlers and didn't manage to set up typescript project.
Maybe someone could create a branch with typescript enabled in this repo https://github.com/Kocal/vue-web-extension-vue3.
Or create separate repo as example of vue 3 typescript project?
