### ISSUE TITLE
Vue CLI 3 or 4

### ISSUE THREAD

**Issue by lelandhwu** [Kocal/vue-web-extension#616]
With the upgrades and migrations to vue CLI 3 and 4, vue CLI 2.0 will inevitably be deprecated it seems.
Are there any plans to migrate this project to use Vue CLI 3 or 4?

**Comment by lelandhwu** [comment]
Nevermind, I just found an old issue that addresses this. Closing now.

**Comment by Kocal** [comment]
Hi, 

Vue CLI 3+ will be supported, see https://github.com/Kocal/vue-web-extension/issues/315#issuecomment-683260650 for more information.
