### ISSUE TITLE
support vue 3 when officially released?

### ISSUE THREAD

**Issue by OmarB97** [Kocal/vue-web-extension#621]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kocal** [comment]
Hi, I don't think I will add Vue 3 support until this template is not compatible with Vue CLI 3 and 4, it will require a lot of works that will be removed when adding Vue CLI 3/4 compatibility.

**Comment by Kocal** [comment]
Hey, since yesterday Vue CLI 3+ support has been added and it should be easier to add Vue 3 support.
However, I don't think it can/should be done in this repository, but in https://github.com/adambullmer/vue-cli-plugin-browser-extension. You can open an issue for that.

**Comment by leoplct** [comment]
Just for clarification. 
If I want to start a new project using VUE 3 should I use this ?
 https://github.com/adambullmer/vue-cli-plugin-browser-extension

**Comment by Kocal** [comment]
Kocal/vue-web-extension is based on https://github.com/adambullmer/vue-cli-plugin-browser-extension, so it won't change anything for you.
