### ISSUE TITLE
Get a Uncaught EvalError: when using the production build of my extension

### ISSUE THREAD

**Issue by bosaengineering** [Kocal/vue-web-extension#637]
**Describe the bug**
After building the production version of my extension, I attempted to load it unpacked. When I do this, I get the following error:

_EvalError:
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"._

It points to the following lines in the code:

File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 61 col 13631 in [anonymous]
File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 61 col 13928 in Object.a40a
File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 1 col 110 in n
File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 1264 col 2266 in Module.<anonymous>
File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 1264 col 7114 in Module.fe77
File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 1 col 110 in n
File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 1 col 3194 in Object.1
File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 1 col 110 in n
File chrome-extension://lkpjgcmldikmmafidjhfbiagckdjbfij/js/background.js line 1 col 908 in [anonymous]

When I load the development code (created by npm serve) I do not get this error. 

I have a suspicion that it could be related to using Vue in development vs production Vue but I can't confirm.

**To Reproduce**
1. unzip production code and load as unpacked on chrome://extensions
2. unpacked extension should load with the Eval error
3. For access to the UI, open a google doc. Content script should inject and UI should appear. 
4. Click on "Sign up with Google" button. Note that it does not work due to eval error.

**Expected behavior**
1. unzip production code and load as unpacked on chrome://extensions
2. unpacked extension should load without Eval error
3. For access to the UI, open a google doc. Content script should inject and UI should appear. 
4. Click on "Sign up with Google" button. The Oauth2 sign up should appear.

**Screenshots**
<img width="707" alt="Screen Shot 2020-10-14 at 11 52 28 AM" src="https://user-images.githubusercontent.com/19141396/96032630-ca87d880-0e13-11eb-99f7-a7e90951f699.png">

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: 2.0.0
 - OS: macOS 10.13.6
 - Node.js version: 12.18.3

**Additional context**

**Comment by Kocal** [comment]
Hi!

I think this is related to https://github.com/adambullmer/vue-cli-plugin-browser-extension, can you open an issue on their repo? 

Thanks

**Comment by bosaengineering** [comment]
@Kocal thank you will do!

**Comment by Kocal** [comment]
Closing since https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/100 has been fixed.
