### ISSUE TITLE
Can't use arrive.js

### ISSUE THREAD

**Issue by mykola-zomchak** [Kocal/vue-web-extension#642]
How can I use https://github.com/uzairfarooq/arrive inside of content with this preset?

**Comment by sherifmayika** [comment]
Can you elaborate what do you want to finally achieve on DOM? If you wan to to export it as content script follow this. `// vue.config.js
module.exports = {
  pluginOptions: {
    browserExtension: {
      componentOptions: {
        // <name of component>: <options>
        // e.g.
        contentScripts: {
          entries: {
            content1: 'src/content-script1.js',
            content2: 'src/content-script2.js',
          },
        },
      },
    },
  },
};`

**Comment by Kocal** [comment]
This question is not related to the preset, if you have issues about understanding and working with a Web extension, you can ask your question on stackoverflow.
