### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by e-roy** [Kocal/vue-web-extension#645]
I like the recent update, this boilerplate is really enjoyable to use.

**Describe the bug**
I'm getting warnings in console logs for both background.js and page tab

(background.js example)
DevTools failed to load SourceMap: Could not load content for chrome-extension://-------------------------/js/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

(page tab example)
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/webextension-polyfill/dist/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

I'm getting multiple in the console log on the page tab

Even the build zipped file has these errors when unpacked.

What am I missing?

**Comment by Kocal** [comment]
Hi,

I was able to get a similar warning on Chrome:
![image](https://user-images.githubusercontent.com/2103975/101401837-3007bb00-38d3-11eb-8ab8-6e4972911f65.png)

The .map files are well generated:
![image](https://user-images.githubusercontent.com/2103975/101401898-47df3f00-38d3-11eb-81da-301561e7e021.png)
 
And in Firefox it works fine:
![image](https://user-images.githubusercontent.com/2103975/101401760-0f3f6580-38d3-11eb-8ead-7cd53d329e6f.png)

I don't know what can happens here, sorry.

**Comment by e-roy** [comment]
I didn't know this boilerplate worked for Firefox also!

So I came across a fix for this issue for Chrome.  

**vue.config.js**

add

```
  "productionSourceMap": false,
  "configureWebpack": {
    "devtool": 'source-map',
  },
```

You will still get warnings in your console log during development, but no longer in production.
