### ISSUE TITLE
Manifest.json file is not included in building

### ISSUE THREAD

**Issue by Shaun-Regenbaum** [Kocal/vue-web-extension#648]
**Describe the bug**
When serving or building, the manifest.json file is not copied to the created dist folder.
**To Reproduce**
1. run or serve
2. look at the dist folder

**Expected behavior**
I expect the manifest.json folder to copy to the dist folder to allow for the dist to be a valid folder to use as a chrome extension

**Comment by Kocal** [comment]
Hi!

Are you using the Vue-CLI 2 boilerplate ([v1](https://github.com/Kocal/vue-web-extension/tree/v1)) or the Vue-CLI 3 preset?
- If using the Vue-CLI 2 boilerplate, you first need to run `yarn build:dev` first to create a `manifest.json` file and then `yarn serve`. Note that no features/bugs will be added on `v1` branch.
- If you are using the Vue-CLI 3 preset, please open a feature request on https://github.com/adambullmer/vue-cli-plugin-browser-extension repository.

Thanks!

**Comment by Kocal** [comment]
@Shaun-Regenbaum how did you solve your issue?

**Comment by Shaun-Regenbaum** [comment]
I built my app from scratch, I would assume that the manifest is not part of the build stage.
