### ISSUE TITLE
content_security_policy issue with compiling for Manifest v3

### ISSUE THREAD

**Issue by grandslammer** [Kocal/vue-web-extension#654]
Specifically, the content_security_policy (auto-generated in dist - it is not in my manifest) - is supposed to be an object in v3, not a string like in v2.

manifest v2:
```
"content_security_policy": "script-src 'self' ; object-src 'self'"
```
should be this in manifest v3:
```
  "content_security_policy": {
    "extension_pages": "script-src 'self' ; object-src 'self'"
  }
```
I have to manually change this in the dist manifest.json every time I compile.Otherwise, Chrome Canary gives an error.

**Comment by Kocal** [comment]
Hi :wave: 

The `manifest.json` is created by https://github.com/adambullmer/vue-cli-plugin-browser-extension, and I see that an issue is already open on https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/107.
Feel free to open a PR if needed.

THanks

**Comment by leoplct** [comment]
Any ideas to fix this? It breaks all extension manifest V3. How can I specify to not add "content_security_policy": "script-src 'self' ; object-src 'self'" ?

**Comment by Kocal** [comment]
> Any ideas to fix this? It breaks all extension manifest V3. How can I specify to not add "content_security_policy": "script-src 'self' ; object-src 'self'" ?

https://github.com/Kocal/vue-web-extension/issues/654#issuecomment-756663110
