### ISSUE TITLE
just by creating the basic app background (and content-script) do not run

### ISSUE THREAD

**Issue by piLeoni** [Kocal/vue-web-extension#655]
**Describe the bug**
I simply tired to install the basic app, and both background and content script did not worked (they did not printed on the respective consoles any message)

**Comment by Kocal** [comment]
Hi, I suppose this is the same issue than #652 ?

**Comment by devglrd** [comment]
No,

The content-script.js is not trigger in the webpage ..

**Comment by devglrd** [comment]
You have to add this to your `manifest.json`


```"content_scripts":
  [
    {
      "matches": ["<all_urls>"],
      "js": ["js/content-script.js"],
      "run_at": "document_end"
    }
  ],```

**Comment by Kocal** [comment]
Closing as resolved.
