### ISSUE TITLE
Can't debug in serve mode

### ISSUE THREAD

**Issue by rkrejcii** [Kocal/vue-web-extension#656]
Hi,

I started using this preset, but have following problem:

When I run 
```
npm run serve
```
the code in DevTools is compiled by Webpack, so I can't use any debugging.

I will be grateful for any hint how to change this behavior.

Thank you
Richard

**Comment by Kocal** [comment]
Hi, you need to build the extension first and load the extension in your browser, then run `npm run serve`. 

That's maybe related to https://vue-web-extension.netlify.app/development/Vue-Devtools.html.

**Comment by OrenLX** [comment]
Hey, I have this issue as well.
So far I can connect it - but there issues on the console:

![image](https://user-images.githubusercontent.com/34863928/116386012-0fa8b080-a822-11eb-819a-4ab63ba141ad.png)

any ideas how can I resolve it?

**Comment by Kocal** [comment]
Hi, looks like your Vue devtools is outdated, see:
- https://www.programmersought.com/article/55686927543/
- https://github.com/vuejs/vue-devtools/issues/1289

Anyway, that's not an issue from vue-web-extension but from vue-devtools
