### ISSUE TITLE
Vuetify stylesheets not added to page in production mode

### ISSUE THREAD

**Issue by farnazj** [Kocal/vue-web-extension#674]
**Describe the bug**
I'm building an extension that inserts a Vue app into any webpage. I'm using Vuetify to style the app. When serving the project in the development mode, Vuetify's stylesheets are inserted into the document (in the head). But when building for production, they are not.

**To Reproduce**

in content script:
```
   import Vue from 'vue';
   import insertedApp from '@/App';
   import vuetify from '@/plugins/vuetify';

    const app = document.createElement('div');
    app.setAttribute('id', 'vueApp');
    document.body.prepend(app);

    new Vue({
        el: '#vueApp',
        vuetify,
        render: h => h(insertedApp),
    });
```

plugins/vuetify.js:
```
import Vue from 'vue';
import Vuetify from 'vuetify/lib/framework';

Vue.use(Vuetify);

export default new Vuetify({
    icons: {
        iconfont: 'mdiSvg'
    }
});

```

**Additional context**
One way to get around this is to use Vuetify's CDN but I don't want to do that because I'm prefixing Vuetify's classes with a custom prefix in vue.config.js so they won't pollute the global namespace.

**Comment by Kocal** [comment]
Hi!

Do you have a .css generated (containing Vuetify CSS) when compiling? Don't you need to import `vuetify/dist/vuetify.min.css`?

**Comment by farnazj** [comment]
Hello!
In dist/css I get a chunk-vendors.some hash.css and a content-script.some hash.css when I compile for build mode which contain Vuetify CSS. But these stylesheets don't seem to be inserted into the webpage when I load the production built extension into Chrome. (actually a question I have is how are they automatically inserted into the webpage when building for development?)
Since I import Vuetify from ```vuetify/lib/framework``` I don't think I need to import from ```vuetify/dist/vuetify.min.css``` . That's what has worked for the dev build and other non- browser extension projects I've worked on.

**Comment by Kocal** [comment]
For production, styles are extracted into a dedicated `.css` file. They are not loaded by your javascript anymore unlike in development (where css extraction is not enabled).

Also for a popup, the HTML file is processed by webpack and it injects CSS/JS files automatically, but this can't work with a content script.

Can you try to disable CSS extraction in your `vue.config.js`? See documentation: https://cli.vuejs.org/config/#css-extract

**Comment by farnazj** [comment]
Oh setting the following in ```vue.config.js``` solved the issue:
```
 css: {
    extract: false
  }
```
Thank you!
