### ISSUE TITLE
Is the repository compatible with Manifest V3

### ISSUE THREAD

**Issue by AutismPatient** [Kocal/vue-web-extension#680]
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: ...
 - OS: ...
 - Node.js version: ...

**Additional context**

**Comment by Kocal** [comment]
See https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/107
